### PR TITLE
Added testimonials div

### PR DESCRIPTION
**Pull request by mayank3810**
Hi,
I am Mayank Gautam. I have added a div for testimonials. Would you please review and merge my pull request?
Thank You!

### CODE REVIEW

**Comment by AnshumanFauzdar** [comment]
@mayank3810 show screenshot of changes

**Comment by mayank3810** [comment]
Hello @AnshumanFauzdar, please find the screenshot below
Screenshot_83
.

**Comment by AnshumanFauzdar** [comment]
Hey @mayank3810 I will suggest to add your own testimonial instead of leaving lorem ipsum.

**Comment by mayank3810** [comment]
Hi @AnshumanFauzdar, I have made the necessary changes
Screenshot_87
.

**Pull request merged**
