### PR TITLE
Updated style.css- Added frame structure to team section

### PR DESCRIPTION
**Pull request by simranquirky**
Screenshot (522)

### CODE REVIEW

**Comment by AnshumanFauzdar** [comment]
Great 🎉

**Comment by simranquirky** [comment]
Are you not accepting for hactoberfest? You have not added the label actually.

**Comment by AnshumanFauzdar** [comment]
@simranquirky this repo is labelled for hacktoberfest. This PR will be accepted as valid hacktoberfest contribution.

**Comment by simranquirky** [comment]
> @simranquirky this repo is labelled for hacktoberfest. This PR will be accepted as valid hacktoberfest contribution.

OK

**Pull request merged**
