### PR TITLE
Updated name to CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Ocoderdude**
Hello maintainer @AnshumanFauzdar ,

I am new to open source, so please merge my pull request.

### Please add ‘hacktoberfest’ & ‘hacktoberfest-accepted’ label to my PR

Reference: https://hacktoberfest.digitalocean.com/hacktoberfest-update

### CODE REVIEW

**Comment by AnshumanFauzdar** [comment]
Hey,

Welcome to open source @Ocoderdude I am happy to merge your PR but you have not followed all the steps given in [readme](https://github.com/AnshumanFauzdar/Hacktoberfest2020/blob/master/README.md) hence please read again and make suitable changes.

Thanks and Regards,
Anshuman Fauzdar

**Comment by Ocoderdude** [comment]
Now it looks like this:

**Comment by Ocoderdude** [comment]
Please verify it @AnshumanFauzdar :)

**Comment by AnshumanFauzdar** [comment]
Hey @Ocoderdude I hope this is not rude but you are not in core team and main idea was to add a div and contribute something you feel looks cool or anything like that :)

**Comment by Ocoderdude** [comment]
Oh @AnshumanFauzdar , Sorry I misunderstood :(

**Comment by Ocoderdude** [comment]
I will make the changes in the website ASAP

**Comment by AnshumanFauzdar** [comment]
No problem chief :) @Ocoderdude

**Pull request closed without merging**
