### PR TITLE
top navigation bar updated by Prashant

### PR DESCRIPTION
**Pull request by prashantkr006**
I have worked on the top navigation bar added relative links of home, our team and contributors so that now user don't need to scroll again and again 
and added a toggle button too for small screen, if you like it you can merge it.

### CODE REVIEW

**Comment by AnshumanFauzdar** [comment]
Hey @prashantkr006 can you please show screenshot of changes.

**Comment by prashantkr006** [comment]
yea sure !
see earlier it used to look like this
image

user had to always scroll down/up to move on the page

I changed it into this
image
I have added relative links to those home, our team and contributers now users don't need to scroll always they just need to click on the options

for small screen added a toggle button too
image

**Comment by AnshumanFauzdar** [comment]
Looking great!

**Comment by prashantkr006** [comment]
thankyou! @AnshumanFauzdar

**Pull request merged**
